// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8rn5v4AC1LpX7FPVESq-4KjoRH9mrqEg',
    appId: '1:383672008400:web:06b5cba50027c9d8f9a8d5',
    messagingSenderId: '383672008400',
    projectId: 'collabify-7b43c',
    authDomain: 'collabify-7b43c.firebaseapp.com',
    storageBucket: 'collabify-7b43c.appspot.com',
    measurementId: 'G-DKSKHLBLDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDcQ5LODQOihDs6jg7PFksfz2G46AUibk',
    appId: '1:383672008400:android:6481bc4af60694a9f9a8d5',
    messagingSenderId: '383672008400',
    projectId: 'collabify-7b43c',
    storageBucket: 'collabify-7b43c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu7zvfei7BHutleRP9Cv45QVyMEUQf0hQ',
    appId: '1:383672008400:ios:0b82db9326f4178af9a8d5',
    messagingSenderId: '383672008400',
    projectId: 'collabify-7b43c',
    storageBucket: 'collabify-7b43c.appspot.com',
    androidClientId: '383672008400-u42ssu8rs9pbd3s94be9q50d1g13dasl.apps.googleusercontent.com',
    iosClientId: '383672008400-k4alt1n8asbua5o1blemm3ie5ne8e15u.apps.googleusercontent.com',
    iosBundleId: 'com.example.classico',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu7zvfei7BHutleRP9Cv45QVyMEUQf0hQ',
    appId: '1:383672008400:ios:0b82db9326f4178af9a8d5',
    messagingSenderId: '383672008400',
    projectId: 'collabify-7b43c',
    storageBucket: 'collabify-7b43c.appspot.com',
    androidClientId: '383672008400-u42ssu8rs9pbd3s94be9q50d1g13dasl.apps.googleusercontent.com',
    iosClientId: '383672008400-k4alt1n8asbua5o1blemm3ie5ne8e15u.apps.googleusercontent.com',
    iosBundleId: 'com.example.classico',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8rn5v4AC1LpX7FPVESq-4KjoRH9mrqEg',
    appId: '1:383672008400:web:dc9a91b06afebe03f9a8d5',
    messagingSenderId: '383672008400',
    projectId: 'collabify-7b43c',
    authDomain: 'collabify-7b43c.firebaseapp.com',
    storageBucket: 'collabify-7b43c.appspot.com',
    measurementId: 'G-2G8KNQSJYR',
  );
}
